### ISSUE TITLE
string.split does not match the spec/Bazel implementation

### ISSUE THREAD

**Issue by allsey87** [facebook/starlark-rust#125]
While I actually find the implementation in starlark-rust better, e.g., it is incredibly useful to be able to do:
```starlark
"a cx   bb s  ".split()
["a", "cx", "bb", "s"]
```
or:
```starlark
"".split()
[]
```
this unfortunately does not match the Bazel implementation/starlark spec which requires `sep` and has no good way of achieving the above as far as I can tell...

**Comment by ndmitchell** [comment]
https://github.com/bazelbuild/starlark/blob/master/spec.md#stringsplit is the specification from the Starlark specification website. Which states:

> If sep is not specified or is None, split uses a different algorithm: it removes all leading spaces from S (or trailing spaces in the case of rsplit), then splits the string around each consecutive non-empty sequence of Unicode white space characters.

Given this also seems to match Python, I'd declare the Bazel implementation to be buggy here.

**Comment by allsey87** [comment]
Interesting! In that case the signature in [Bazel's documentation](https://bazel.build/rules/lib/core/string#split) contradicts the standard. Moreover using split without an argument (in Bazel 7.2.1) throws an error regarding the missing argument `sep`.

Related: https://github.com/bazelbuild/starlark/issues/176

Closing since this indeed seems like an issue with Bazel's implementation.

**Comment by allsey87** [comment]
@ndmitchell actually there is still a difference from [the standard](https://github.com/bazelbuild/starlark/blob/master/spec.md#stringsplit). Looking at the examples, `"a cx   bb s  ".split()` should only return `["a", "cx", "bb", "s"]` if `maxsplit` was `1`, otherwise there should be additional empty strings in the returned array. This is not the case with the starlark-rust implementation.

**Comment by ndmitchell** [comment]
I think that starlark-rust is right there, following the guidance around "If sep is not specified or is None, split uses a different algorithm". Concretely:

```
C:\Neil\starlark-rust>cargo run -- -e "'a cx  bb s  '.split()"  
1 files, 0 errors, 0 warnings, 0 advices, 0 disabled

C:\Neil\starlark-rust>cargo run -- -e "'a cx  bb s  '.split(' ')" 
["a", "cx", "", "bb", "s", "", ""]
```

Why do you think `"a cx  bb s  ".split()` should return as you describe?

**Comment by allsey87** [comment]
You are right. I got confused (again). Closing!
