### ISSUE TITLE
Not working in oss-fuzz

### ISSUE THREAD

**Issue by ndmitchell** [facebook/starlark-rust#128]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70230 shows that Starlark no longer works in oss-fuzz. The error is:

```
Step #3 - "compile-libfuzzer-address-x86_64": [0m[1m[38;5;9merror[E0658][0m[0m[1m: `#[diagnostic]` attribute name space is experimental[0m
Step #3 - "compile-libfuzzer-address-x86_64": [0m   [0m[0m[1m[38;5;12m--> [0m[0m/rust/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.208/src/de/mod.rs:537:5[0m
Step #3 - "compile-libfuzzer-address-x86_64": [0m    [0m[0m[1m[38;5;12m|[0m
Step #3 - "compile-libfuzzer-address-x86_64": [0m[1m[38;5;12m537[0m[0m [0m[0m[1m[38;5;12m|[0m[0m [0m[0m    diagnostic::on_unimplemented([0m
Step #3 - "compile-libfuzzer-address-x86_64": [0m    [0m[0m[1m[38;5;12m| [0m[0m    [0m[0m[1m[38;5;9m^^^^^^^^^^[0m
Step #3 - "compile-libfuzzer-address-x86_64": [0m    [0m[0m[1m[38;5;12m|[0m
Step #3 - "compile-libfuzzer-address-x86_64": [0m    [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: see issue #111996 <https://github.com/rust-lang/rust/issues/111996> for more information[0m
Step #3 - "compile-libfuzzer-address-x86_64": [0m    [0m[0m[1m[38;5;12m= [0m[0m[1mhelp[0m[0m: add `#![feature(diagnostic_namespace)]` to the crate attributes to enable[0m
Step #3 - "compile-libfuzzer-address-x86_64": [0m    [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: this compiler was built on 2024-02-11; consider upgrading it if it is out of date[0m
```

So the compiler defaults to coming from February which no longer works with the latest version of serde. The right solution would be to use the most recent version of Rust. I don't know why oss-fuzz doesn't do that by default? CC @silvergasp who set this up originally and might have some ideas.

**Comment by silvergasp** [comment]
I'll take a squiz

**Comment by silvergasp** [comment]
I don't know why the nightly rustc (which oss-fuzz uses) isn't updated regularly in the base rust images. But it's an easy enough fix to just update it in the starlark-rust Docker image. Attempting fix with https://github.com/google/oss-fuzz/pull/12404 I tested this locally so I expect the CI to pass as well.

**Comment by silvergasp** [comment]
That's all merged now, so I expect it'll be fixed on the next round of nightly builds (so in the next 24hrs or so).

**Comment by silvergasp** [comment]
This is fixed now! https://oss-fuzz-build-logs.storage.googleapis.com/index.html#starlark-rust

**Comment by ndmitchell** [comment]
Thanks!
