### ISSUE TITLE
starlark-bin: unable to load files

### ISSUE THREAD

**Issue by s-zeng** [facebook/starlark-rust#137]
Hello, when running the starlark bin executable, load statements don't work. It seems like the bin fails to call `Evaluator.set_loader` at any point. Example:

```
$ starlark --version
starlark 0.12.0
$ starlark
$> load("lib.star", "a")
error: No imports are available, you tried `lib.star` (no call to `Evaluator.set_loader`)
 --> expression:1:1
  |
1 | load("lib.star", "a")
  | ^^^^^^^^^^^^^^^^^^^^^
  |
```

**Comment by ndmitchell** [comment]
Generally Starlark doesn't specify what a load statement is. But I think its reasonable for the Starlark binary to just treat strings as file paths and see what happens. I'm working on a diff to do that. Note that in most cases the Starlark binary is a demo, and most people need to build their own Starlark with custom builtins etc.

**Comment by ndmitchell** [comment]
This should now work since 2fd96193280a04c581f0c8feb5bb8b9b8f63d5d0
