### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by freeform-andre** [facebook/starlark-rust#138]
It seems like it's been a while and I'm finding more and more things in `main` that aren't in the latest release and are valuable.

Thanks!

**Comment by ndmitchell** [comment]
Great point. I just sent up a diff internally to fix #137. I'll make a release once that is landed.

**Comment by freeform-andre** [comment]
Looks like [release 0.13.0](https://github.com/facebook/starlark-rust/releases/tag/v0.13.0) is out, thank you!
