### ISSUE TITLE
lsp suggestions are too aggressive

### ISSUE THREAD

**Issue by cjhopman** [facebook/starlark-rust#85]
For example: we pop up a bunch of suggestions after typing record( we do it quickly enough that when the user hits enter to start defining the record fields, they actually just accept the suggestion :/

also happens at a trailing `,` which is also common

**Comment by cjhopman** [comment]
@MaartenStaa I'd made a bunch of internal issues for annoyances I'd noticed when using the extension to track so I could get to fixing them later, but given that you're doing some great work on the lsp/extension I thought I'd copy them out to github in case you're interested in more opportuninties for improvements there. There's this one and like 6 or 7 others I just filed.

**Comment by cameron-martin** [comment]
I presume this is fixed by 4be1b3bbf38dbddfca9aabacbff82a644681ae9d?
